//colors
#define  BGND   0x38   //lilac
#define  ORNG   0x42   //orange
#define  WHTE   0x0F   //white
#define  GRAY   0x07   //gray
#define  DGRN   0xBD   //dark green
#define  LGRN   0x76   //light green

// bitmaps
int hare[]={
  ORNG, ORNG, ORNG, ORNG, 0x00, 0x00, ORNG, 0x00, 0x00, ORNG, ORNG, ORNG, ORNG,
  ORNG, ORNG, ORNG, 0x00, WHTE, 0x00, ORNG, 0x00, WHTE, 0x00, ORNG, ORNG, ORNG,
  ORNG, ORNG, 0x00, WHTE, WHTE, 0x00, ORNG, 0x00, WHTE, WHTE, 0x00, ORNG, ORNG,
  ORNG, ORNG, 0x00, WHTE, WHTE, 0x00, ORNG, 0x00, WHTE, WHTE, 0x00, ORNG, ORNG,
  ORNG, ORNG, 0x00, WHTE, WHTE, 0x00, ORNG, 0x00, WHTE, WHTE, 0x00, ORNG, ORNG,
  ORNG, ORNG, 0x00, WHTE, WHTE, 0x00, ORNG, 0x00, WHTE, WHTE, 0x00, ORNG, ORNG,
  ORNG, ORNG, 0x00, WHTE, WHTE, 0x00, ORNG, 0x00, WHTE, WHTE, 0x00, ORNG, ORNG,
  ORNG, ORNG, 0x00, WHTE, GRAY, 0x00, ORNG, 0x00, GRAY, WHTE, 0x00, ORNG, ORNG,
  ORNG, ORNG, 0x00, WHTE, GRAY, 0x00, ORNG, 0x00, GRAY, WHTE, 0x00, ORNG, ORNG,
  ORNG, ORNG, ORNG, 0x00, GRAY, GRAY, 0x00, GRAY, GRAY, 0x00, ORNG, ORNG, ORNG,
  ORNG, ORNG, 0x00, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, 0x00, ORNG, ORNG,
  ORNG, 0x00, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, 0x00, ORNG,
  ORNG, 0x00, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, 0x00, ORNG,
  0x00, GRAY, GRAY, 0x00, GRAY, GRAY, GRAY, GRAY, GRAY, 0x00, GRAY, GRAY, 0x00,
  0x00, GRAY, GRAY, 0x00, WHTE, WHTE, 0x00, WHTE, WHTE, 0x00, GRAY, GRAY, 0x00,
  0x00, GRAY, WHTE, WHTE, WHTE, WHTE, WHTE, WHTE, WHTE, WHTE, WHTE, GRAY, 0x00,
  ORNG, 0x00, WHTE, WHTE, WHTE, WHTE, WHTE, WHTE, WHTE, WHTE, WHTE, 0x00, ORNG,
  ORNG, ORNG, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, ORNG, ORNG
};
int turtle[]={
  ORNG, ORNG, ORNG, ORNG, ORNG, ORNG, LGRN, LGRN, LGRN, ORNG, ORNG, ORNG, ORNG, ORNG, ORNG, ORNG, ORNG, ORNG,
  ORNG, ORNG, ORNG, ORNG, ORNG, LGRN, LGRN, LGRN, LGRN, LGRN, ORNG, ORNG, ORNG, ORNG, ORNG, ORNG, ORNG, ORNG,
  ORNG, ORNG, ORNG, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, ORNG, DGRN, DGRN, DGRN, DGRN, ORNG,
  ORNG, ORNG, ORNG, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, ORNG, DGRN, DGRN, 0x00, DGRN, DGRN,
  ORNG, ORNG, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, DGRN, DGRN, 0x00, DGRN, DGRN,
  ORNG, ORNG, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, DGRN, DGRN, DGRN, DGRN, DGRN,
  ORNG, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, DGRN, DGRN, DGRN, DGRN,
  DGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, DGRN, DGRN, ORNG, ORNG,
  DGRN, DGRN, DGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, DGRN, DGRN, DGRN, ORNG, ORNG, ORNG,
  ORNG, ORNG, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, ORNG, ORNG, ORNG, ORNG, ORNG,
  ORNG, ORNG, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, ORNG, ORNG, ORNG, ORNG, ORNG,
  ORNG, ORNG, DGRN, DGRN, DGRN, ORNG, ORNG, ORNG, ORNG, ORNG, DGRN, DGRN, DGRN, ORNG, ORNG, ORNG, ORNG, ORNG
};
int draw1[]={
  BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,0x00,BGND,0x00,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,
  BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,0x00,WHTE,0x00,WHTE,0x00,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,
  BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,0x00,WHTE,0x00,WHTE,0x00,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,
  BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,0x00,WHTE,0x00,GRAY,0x00,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,
  BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,0x00,GRAY,0x00,GRAY,0x00,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,
  BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,0x00,GRAY,0x00,GRAY,0x00,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,
  BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,0x00,0x00,0x00,GRAY,GRAY,0x00,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,
  BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,0x00,GRAY,GRAY,GRAY,GRAY,GRAY,0x00,0x00,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,
  BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,0x00,GRAY,0x00,WHTE,WHTE,GRAY,GRAY,GRAY,0x00,BGND,BGND,0x00,0x00,BGND,BGND,BGND,BGND,BGND,BGND,
  BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,0x00,WHTE,0x00,WHTE,WHTE,WHTE,GRAY,GRAY,WHTE,0x00,0x00,WHTE,WHTE,0x00,0x00,BGND,BGND,BGND,BGND,
  BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,0x00,WHTE,WHTE,WHTE,WHTE,WHTE,WHTE,WHTE,GRAY,WHTE,WHTE,WHTE,WHTE,GRAY,GRAY,0x00,0x00,BGND,BGND,BGND,
  BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,0x00,WHTE,WHTE,WHTE,WHTE,WHTE,WHTE,WHTE,WHTE,WHTE,WHTE,WHTE,GRAY,GRAY,GRAY,GRAY,0x00,0x00,BGND,BGND,
  BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,BGND,0x00,0x00,WHTE,0x00,WHTE,WHTE,WHTE,WHTE,WHTE,WHTE,GRAY,GRAY,WHTE,GRAY,GRAY,GRAY,0x00,BGND,BGND,
  BGND,BGND,BGND,0x00,BGND,BGND,BGND,0x00,BGND,BGND,BGND,BGND,BGND,0x00,0x00,WHTE,WHTE,WHTE,WHTE,WHTE,WHTE,0x00,0x00,WHTE,WHTE,GRAY,GRAY,0x00,0x00,BGND,
  BGND,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,BGND,BGND,BGND,0x00,WHTE,WHTE,WHTE,WHTE,WHTE,WHTE,WHTE,0x00,WHTE,WHTE,GRAY,GRAY,GRAY,0x00,WHTE,0x00,
  BGND,BGND,0x00,BGND,BGND,BGND,BGND,BGND,0x00,BGND,BGND,BGND,BGND,0x00,WHTE,WHTE,WHTE,WHTE,0x00,0x00,0x00,0x00,WHTE,WHTE,GRAY,WHTE,WHTE,WHTE,WHTE,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,BGND,0x00,WHTE,WHTE,WHTE,0x00,0x00,WHTE,WHTE,WHTE,WHTE,WHTE,WHTE,GRAY,GRAY,0x00,0x00,0x00,BGND,
  BGND,0x00,BGND,BGND,BGND,BGND,BGND,BGND,BGND,0x00,BGND,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,BGND,BGND,BGND
};
int draw2[]={
  BGND, BGND, BGND, BGND, BGND, BGND, LGRN, LGRN, LGRN, BGND, BGND, BGND, BGND, BGND, BGND, BGND, BGND, BGND,
  BGND, BGND, BGND, BGND, BGND, LGRN, LGRN, LGRN, LGRN, LGRN, BGND, BGND, BGND, BGND, BGND, BGND, BGND, BGND,
  BGND, BGND, BGND, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, BGND, DGRN, DGRN, DGRN, DGRN, BGND,
  BGND, BGND, BGND, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, BGND, DGRN, DGRN, 0x00, DGRN, DGRN,
  BGND, BGND, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, DGRN, DGRN, 0x00, DGRN, DGRN,
  BGND, BGND, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, DGRN, DGRN, DGRN, DGRN, DGRN,
  BGND, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, DGRN, DGRN, DGRN, DGRN,
  DGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, DGRN, DGRN, BGND, BGND,
  DGRN, DGRN, DGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, LGRN, DGRN, DGRN, DGRN, BGND, BGND, BGND,
  BGND, BGND, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, BGND, BGND, BGND, BGND, BGND,
  BGND, BGND, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, DGRN, BGND, BGND, BGND, BGND, BGND,
  BGND, BGND, DGRN, DGRN, DGRN, BGND, BGND, BGND, BGND, BGND, DGRN, DGRN, DGRN, BGND, BGND, BGND, BGND, 0x00
};
